// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_totalscore = "CgkIk_ia7fkOEAIQAQ"; // <GPGSID>
        public const string achievement_welcome = "CgkIk_ia7fkOEAIQCA"; // <GPGSID>
        public const string achievement_scoring_over_3000 = "CgkIk_ia7fkOEAIQBw"; // <GPGSID>

        public const string leaderboard_level_1_scoreboard = "CgkIk_ia7fkOEAIQAg"; // <GPGSID>
        public const string leaderboard_level_2_scoreboard = "CgkIk_ia7fkOEAIQAw"; // <GPGSID>
        public const string leaderboard_level_3_scoreboard = "CgkIk_ia7fkOEAIQBA"; // <GPGSID>
        public const string leaderboard_level_4_scoreboard = "CgkIk_ia7fkOEAIQBQ"; // <GPGSID>
        public const string leaderboard_level_5_scoreboard = "CgkIk_ia7fkOEAIQBg"; // <GPGSID>


        public static string[] leaderboardLevels = { "CgkIk_ia7fkOEAIQAg", "CgkIk_ia7fkOEAIQAw", "CgkIk_ia7fkOEAIQBQ", "CgkIk_ia7fkOEAIQBA", "CgkIk_ia7fkOEAIQBg" };


}

